# Generated by Django 3.1.7 on 2021-04-22 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('dob', models.TimeField(default=datetime.datetime(2021, 4, 22, 15, 17, 12, 47122, tzinfo=utc))),
            ],
        ),
    ]
